stages:
  - user
  - testj
  - build

user:
  stage: user
  script: whoami

testj:
  stage: testj
  script: java -version

build:
  stage: build
  script: ./gradlew :web:prepareS3Upload :web:createDraftBundleZip :web:mergeDeploy -Pgdraft=true